---
title: "Untitled"
author: "Marcelo Cubero Sibaja"
date: "22/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r paquetes , warning=FALSE, message=FALSE}
defaultEncoding <- "UTF8"
library(dplyr)
library(sf)
library(terra)
library(raster)
library(DT)
library(ggplot2)
library(plotly)
library(leaflet)

```

```{r datos , warning=FALSE, message=FALSE}
casos <-
  st_read(
    "/vsicurl/https://marcelocubero.github.io/capas_proyecto/casos.geojson",
    quiet = TRUE
  )
casos <-
  casos %>%
  st_transform(4326)

casos_ <-
    read.csv( file= "https://marcelocubero.github.io/capas_proyecto/casos_.csv",
              sep = ",", encoding = "UTF-8") 


fallecidos <- rast("/vsicurl/https://marcelocubero.github.io/capas_proyecto/fallecidos.tif")

```

```{r mapa , warning=FALSE, message=FALSE}

fallecidos_rl <- raster::raster(fallecidos)
bins <- c(10, 100, 500, 1000, 4000, 7600)
pal <- colorBin("Blues", domain = casos$activos, bins = bins)

leaflet() %>%
  addTiles(group="OSM") %>% 
  addProviderTiles(providers$Esri.NatGeoWorldMap , group="NatGeo") %>% 
  addProviderTiles(providers$CartoDB.DarkMatter, group="CartoDB-Black") %>%
  addRasterImage(
    fallecidos_rl, 
    opacity = 0.7,
    group= "Fallecidos",
  ) %>%
  addPolygons(
    data = casos,
    color = "black",
    fillColor = ~pal(activos),
    fillOpacity = 0.7,
    weight = 1,
    opacity = 1,
    stroke = TRUE,
    group= "Casos Activos"
  ) %>%
  addLegend(pal = pal, values = casos$activos, opacity = 0.7, title = "Casos Activos") %>%
  addLayersControl(
    baseGroups = c("OSM", "NatGeo", "CartoDB-Black"),
    overlayGroups = c("Fallecidos", "Casos Activos"),
    options = layersControlOptions(collapsed = FALSE)
  ) 






```

```{r consulta , warning=FALSE, message=FALSE}



casos_ %>%
  select(Cantón= canton,Provincia= provincia, Casos_Activos= activos, Casos_Positivos= positivos) %>%
datatable( casos_, options = list(
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'),
  pageLength = 5
))


```

```{r}
ggplot(casos_, aes(x= canton, y= positivos)) +
  geom_col( width = 0.5, fill= "#008080") +
  ggtitle("Casos Positivos por cantón") +
  xlab("Cantón") +
  ylab("Cantidad de casos positivos") +
   theme(
    plot.title = element_text(size = 16, face = "bold"),
    text = element_text(size=8),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) 
```
```{r}
ggplot(casos_, aes(x= canton, y= activos)) +
  geom_col( width = 0.5, fill= "#00FF7F") +
  ggtitle("Casos Activos por cantón") +
  xlab("Cantón") +
  ylab("Cantidad de casos activos") +
   theme(
    plot.title = element_text(size = 16, face = "bold"),
    text = element_text(size=8),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) 
```

```{r}

bins <- c(10, 100, 500, 1000, 4000, 7600)
pal <- colorBin("Blues", domain = casos$activos, bins = bins)


leaflet() %>%
  addTiles() %>%
  addPolygons(
    data = casos,
    color = "black",
    fillColor = ~pal(activos),
    fillOpacity = 0.7,
    weight = 1,
    opacity = 1,
    stroke = TRUE,
    group= "Casos"
  ) %>%
  addLegend(pal = pal, values = casos$activos, opacity = 0.7, title = "Casos Activos")



```
```{r}
at <- seq(1:800)
pal1 <- colorBin('Accent', domain = at ,na.color = "transparent")

 
leaflet() %>%
  addTiles() %>% 
  addRasterImage(
    fallecidos_rl, 
    opacity = 1,
    group= "Fallecidos",
    colors = pal1
  ) %>%
  addLegend("bottomleft", pal = pal1, values = at, title = "Fallecidos")

```




```{r}
fallecidos_rl <- raster::raster(fallecidos)
bins <- c(10, 100, 500, 1000, 4000, 7600)
pal <- colorBin("Blues", domain = casos$activos, bins = bins)
at <- seq(1:800)
pal1 <- colorBin('Accent', domain = at ,na.color = "transparent")


leaflet() %>%
  addTiles(group="OSM") %>% 
  addProviderTiles(providers$Esri.NatGeoWorldMap , group="NatGeo") %>% 
  addProviderTiles(providers$CartoDB.DarkMatter, group="CartoDB-Black") %>%
  addRasterImage(
    fallecidos_rl, 
    opacity = 1,
    group= "Fallecidos",
    colors = pal1
  ) %>%
  addLegend("bottomleft", pal = pal1, values = at, title = "Fallecidos") %>%
  addPolygons(
    data = casos,
    color = "black",
    fillColor = ~pal(activos),
    fillOpacity = 0.7,
    weight = 1,
    opacity = 1,
    stroke = TRUE,
    group= "Casos Activos"
  ) %>%
  addLegend(pal = pal, values = casos$activos, opacity = 0.7, title = "Casos Activos") %>%
  addLayersControl(
    baseGroups = c("OSM", "NatGeo", "CartoDB-Black"),
    overlayGroups = c("Fallecidos", "Casos Activos"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  addScaleBar("bottomright")


```













